# ~/benchmaster/agent/fleet_manager.py

import logging
import time
import os
import requests
from datetime import datetime, timedelta
from typing import List, Dict, Any, Optional

from sqlalchemy import func
from db.models import get_engine, init_db, Machine, BenchmarkJob, Result, Alert

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s [%(levelname)s] %(name)s: %(message)s'
)
logger = logging.getLogger("FleetManager")

# --- Configuration (from Environment Variables) ---
# Note: In production, these should be set in your .env or system environment.
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN")
TELEGRAM_CHAT_ID = os.getenv("TELEGRAM_CHAT_ID")
DB_URL = os.getenv("DATABASE_URL", "sqlite:///~/benchmaster/db/benchmaster.db")

class FleetManager:
    """
    The core component responsible for managing the fleet of Windows host agents.
    Handles health monitoring, anomaly detection, and active alerting.
    """

    def __init__(self, db_url: str = DB_URL):
        self.db_url = db_url
        self.engine = get_engine(self.db_url)
        init_db(self.engine)

    # --- Notification Helpers ---

    def _send_telegram_message(self, message: str):
        """
        Sends a formatted message to the configured Telegram chat via Bot API.
        """
        if not TELEGRAM_BOT_TOKEN or not TELEGRAM_CHAT_ID:
            logger.warning("Telegram credentials missing. Notification skipped.")
            return

        url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"
        payload = {
            "chat_id": TELEGRAM_CHAT_ID,
            "text": message,
            "parse_mode": "Markdown"
        }

        try:
            response = requests.post(url, json=payload, timeout=10)
            response.raise_for_status()
            logger.info("Telegram notification sent successfully.")
        except Exception as e:
            logger.error(f"Failed to send Telegram notification: {e}")

    def _notify(self, alert_type: str, message: str):
        """
        Helper to log to console, DB, and Telegram.
        """
        logger.warning(f"[{alert_type}] {message}")
        
        # Format Telegram message with icons
        icon = "⚠️" if alert_type != "INFO" else "ℹ️"
        formatted_msg = f"{icon} *BenchMaster Alert*\n\n*Type:* {alert_type}\n*Message:* {message}\n\n_Generated by BenchMaster Agent_"
        
        self._send_telegram_message(formatted_msg)

    # --- Monitoring Logic ---

    def check_machine_health(self, session) -> int:
        """
        Identifies machines that have gone offline (no heartbeat for > 10 minutes).
        """
        offline_threshold = datetime.utcnow() - timedelta(minutes=10)
        offline_machines = session.query(Machine).filter(
            Machine.last_heartbeat < offline_threshold
        ).all()

        count = 0
        for machine in offline_machines:
            # Avoid duplicate alerts for the same offline event
            already_alerted = session.query(Alert).filter(
                Alert.machine_id == machine.id,
                Alert.alert_type == "OFFLINE",
                Alert.acknowledged == False
            ).first()

            if not already_alerted:
                msg = f"Machine *{machine.hostname}* ({machine.ip}) is OFFLINE. Last heartbeat: {machine.last_heartbeat}"
                
                # 1. DB Logging
                new_alert = Alert(
                    machine_id=machine.id,
                    alert_type="OFFLINE",
                    message=msg,
                    created_at=datetime.utcnow()
                )
                session.add(new_alert)
                
                # 2. Telegram Notification
                self._notify("OFFLINE", msg)
                count += 1
        
        return count

    def check_score_anomalies(self, session):
        """
        Detects if the latest benchmark result is significantly lower than the 7-day average.
        """
        # Get all unique machine-benchmark pairs
        pairs = session.query(Machine.id, Result.benchmark).join(Result, Machine.id == Result.machine_id).distinct().all()

        for machine_id, benchmark in pairs:
            # Get the latest result
            latest_result = session.query(Result).filter(
                Result.machine_id == machine_id,
                Result.benchmark == benchmark
            ).order_by(Result.timestamp.desc()).first()

            if not latest_result:
                continue

            # Calculate the 7-day average (excluding the latest result)
            seven_days_ago = datetime.utcnow() - timedelta(days=7)
            
            # Note: We need to handle the JSON extraction based on the DB engine (SQLite vs Postgres)
            # For this implementation, we assume the result.scores_json is already a dict (SQLAlchemy handles this)
            
            # We'll perform a manual average in Python for maximum compatibility
            all_recent_scores = session.query(Result.scores_json).filter(
                Result.machine_id == machine_id,
                Result.benchmark == benchmark,
                Result.timestamp >= seven_days_ago,
                Result.id != latest_result.id
            ).all()
            
            if not all_recent_scores:
                continue

            scores_list = []
            for row in all_recent_scores:
                scores_dict = row[0]
                if scores_dict:
                    # We'll use the first available metric as the 'main' score for comparison
                    # In a real system, we'd match the metric key.
                    vals = list(scores_dict.values())
                    if vals:
                        scores_list.append(float(vals[0]))

            if scores_list:
                avg_score = sum(scores_list) / len(scores_list)
                
                # Extract current score
                current_scores = latest_result.scores_json
                current_val = next(iter(current_scores.values())) if current_scores else None

                if current_val and current_val < (avg_score * 0.85): # 15% drop threshold
                    msg = f"⚠️ *Score Anomaly Detected*\n\nBenchmark: `{benchmark}`\nMachine: `{latest_result.machine_id}`\nScore: `{current_val:.2f}` (Avg: `{avg_score:.2f}`)"
                    
                    new_alert = Alert(
                        machine_id=machine_id,
                        result_id=latest_result.id,
                        alert_type="LOW_SCORE",
                        message=msg,
                        created_at=datetime.utcnow()
                    )
                    session.add(new_alert)
                    self._notify("LOW_SCORE", msg)

    def run_monitoring_cycle(self):
        """
        Executes one complete monitoring cycle.
        """
        from sqlalchemy.orm import sessionmaker
        from db.models import get_session
        
        session = get_session(self.engine)
        try:
            logger.info("Starting monitoring cycle...")
            self.check_machine_health(session)
            self.check_score_anomalies(session)
            session.commit()
            logger.info("Monitoring cycle completed.")
        except Exception as e:
            session.rollback()
            logger.error(f"Cycle failed: {e}")
        finally:
            session.close()

    def start_continuous_monitoring(self, interval_seconds: int = 300):
        """
        Runs the monitoring cycle continuously.
        """
        self.is_running = True
        logger.info(f"Continuous monitoring started (interval: {interval_seconds}s).")
        try:
            while self.is_running:
                self.run_monitoring_cycle()
                time.sleep(interval_seconds)
        except KeyboardInterrupt:
            logger.info("Stopped by user.")
        finally:
            self.is_running = False

if __name__ == "__main__":
    manager = FleetManager()
    manager.start_continuous_monitoring()
